[package]
edition = "2018"
name = "kyanite"
version = "0.2.0"
authors = ["AXAz0r <thealeksaradovic@gmail.com>"]
keywords = ["image", "scrapper", "gallery"]
license = "GPL-3.0"
readme = "README.md"
repository = "https://gitlab.com/lu-ci/kyanite"
description = "A modular, expandable, gallery collector."

[profile.release]
opt-level = 3
lto = true

[dependencies]
clap = "2.33.0"
flate2 = "1.0.13"
md5 = "0.7.0"
reqwest = "0.9.24"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.44"
